// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.newsroom.login.proto.rpc;

public interface DataOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.newsroom.login.proto.rpc.Data)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string userID = 1;</code>
     */
    java.lang.String getUserID();

    /**
     * <code>string userID = 1;</code>
     */
    com.google.protobuf.ByteString getUserIDBytes();
}
