// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.newsroom.login.proto.rpc;

/**
 * Protobuf type {@code com.newsroom.login.proto.rpc.LoginRequest}
 */
public final class LoginRequest extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.newsroom.login.proto.rpc.LoginRequest)
        LoginRequestOrBuilder {
    // Use LoginRequest.newBuilder() to construct.
    private LoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private LoginRequest() {
        mailID_ = "";
        mob_ = "";
        password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private LoginRequest(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                case 0:
                    done = true;
                    break;
                default: {
                    if (!input.skipField(tag)) {
                        done = true;
                    }
                    break;
                }
                case 10: {
                    java.lang.String s = input.readStringRequireUtf8();

                    mailID_ = s;
                    break;
                }
                case 18: {
                    java.lang.String s = input.readStringRequireUtf8();

                    mob_ = s;
                    break;
                }
                case 26: {
                    java.lang.String s = input.readStringRequireUtf8();

                    password_ = s;
                    break;
                }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.newsroom.login.proto.rpc.LoginRequest.class,
                        com.newsroom.login.proto.rpc.LoginRequest.Builder.class);
    }

    public static final int MAILID_FIELD_NUMBER = 1;
    private volatile java.lang.Object mailID_;

    /**
     * <code>string mailID = 1;</code>
     */
    public java.lang.String getMailID() {
        java.lang.Object ref = mailID_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            mailID_ = s;
            return s;
        }
    }

    /**
     * <code>string mailID = 1;</code>
     */
    public com.google.protobuf.ByteString getMailIDBytes() {
        java.lang.Object ref = mailID_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            mailID_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int MOB_FIELD_NUMBER = 2;
    private volatile java.lang.Object mob_;

    /**
     * <code>string mob = 2;</code>
     */
    public java.lang.String getMob() {
        java.lang.Object ref = mob_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            mob_ = s;
            return s;
        }
    }

    /**
     * <code>string mob = 2;</code>
     */
    public com.google.protobuf.ByteString getMobBytes() {
        java.lang.Object ref = mob_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            mob_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PASSWORD_FIELD_NUMBER = 3;
    private volatile java.lang.Object password_;

    /**
     * <code>string password = 3;</code>
     */
    public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            password_ = s;
            return s;
        }
    }

    /**
     * <code>string password = 3;</code>
     */
    public com.google.protobuf.ByteString getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
            password_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (!getMailIDBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, mailID_);
        }
        if (!getMobBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, mob_);
        }
        if (!getPasswordBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, password_);
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (!getMailIDBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, mailID_);
        }
        if (!getMobBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, mob_);
        }
        if (!getPasswordBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, password_);
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.newsroom.login.proto.rpc.LoginRequest)) {
            return super.equals(obj);
        }
        com.newsroom.login.proto.rpc.LoginRequest other = (com.newsroom.login.proto.rpc.LoginRequest) obj;

        boolean result = true;
        result = result && getMailID().equals(other.getMailID());
        result = result && getMob().equals(other.getMob());
        result = result && getPassword().equals(other.getPassword());
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + MAILID_FIELD_NUMBER;
        hash = (53 * hash) + getMailID().hashCode();
        hash = (37 * hash) + MOB_FIELD_NUMBER;
        hash = (53 * hash) + getMob().hashCode();
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.newsroom.login.proto.rpc.LoginRequest parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.newsroom.login.proto.rpc.LoginRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code com.newsroom.login.proto.rpc.LoginRequest}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.newsroom.login.proto.rpc.LoginRequest)
            com.newsroom.login.proto.rpc.LoginRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.newsroom.login.proto.rpc.LoginRequest.class,
                            com.newsroom.login.proto.rpc.LoginRequest.Builder.class);
        }

        // Construct using com.newsroom.login.proto.rpc.LoginRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            mailID_ = "";

            mob_ = "";

            password_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginRequest_descriptor;
        }

        public com.newsroom.login.proto.rpc.LoginRequest getDefaultInstanceForType() {
            return com.newsroom.login.proto.rpc.LoginRequest.getDefaultInstance();
        }

        public com.newsroom.login.proto.rpc.LoginRequest build() {
            com.newsroom.login.proto.rpc.LoginRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.newsroom.login.proto.rpc.LoginRequest buildPartial() {
            com.newsroom.login.proto.rpc.LoginRequest result = new com.newsroom.login.proto.rpc.LoginRequest(this);
            result.mailID_ = mailID_;
            result.mob_ = mob_;
            result.password_ = password_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.newsroom.login.proto.rpc.LoginRequest) {
                return mergeFrom((com.newsroom.login.proto.rpc.LoginRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.newsroom.login.proto.rpc.LoginRequest other) {
            if (other == com.newsroom.login.proto.rpc.LoginRequest.getDefaultInstance())
                return this;
            if (!other.getMailID().isEmpty()) {
                mailID_ = other.mailID_;
                onChanged();
            }
            if (!other.getMob().isEmpty()) {
                mob_ = other.mob_;
                onChanged();
            }
            if (!other.getPassword().isEmpty()) {
                password_ = other.password_;
                onChanged();
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            com.newsroom.login.proto.rpc.LoginRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.newsroom.login.proto.rpc.LoginRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object mailID_ = "";

        /**
         * <code>string mailID = 1;</code>
         */
        public java.lang.String getMailID() {
            java.lang.Object ref = mailID_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                mailID_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string mailID = 1;</code>
         */
        public com.google.protobuf.ByteString getMailIDBytes() {
            java.lang.Object ref = mailID_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                mailID_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string mailID = 1;</code>
         */
        public Builder setMailID(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            mailID_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string mailID = 1;</code>
         */
        public Builder clearMailID() {

            mailID_ = getDefaultInstance().getMailID();
            onChanged();
            return this;
        }

        /**
         * <code>string mailID = 1;</code>
         */
        public Builder setMailIDBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            mailID_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object mob_ = "";

        /**
         * <code>string mob = 2;</code>
         */
        public java.lang.String getMob() {
            java.lang.Object ref = mob_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                mob_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string mob = 2;</code>
         */
        public com.google.protobuf.ByteString getMobBytes() {
            java.lang.Object ref = mob_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                mob_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string mob = 2;</code>
         */
        public Builder setMob(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            mob_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string mob = 2;</code>
         */
        public Builder clearMob() {

            mob_ = getDefaultInstance().getMob();
            onChanged();
            return this;
        }

        /**
         * <code>string mob = 2;</code>
         */
        public Builder setMobBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            mob_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object password_ = "";

        /**
         * <code>string password = 3;</code>
         */
        public java.lang.String getPassword() {
            java.lang.Object ref = password_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                password_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <code>string password = 3;</code>
         */
        public com.google.protobuf.ByteString getPasswordBytes() {
            java.lang.Object ref = password_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b = com.google.protobuf.ByteString.copyFromUtf8((java.lang.String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <code>string password = 3;</code>
         */
        public Builder setPassword(java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            password_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>string password = 3;</code>
         */
        public Builder clearPassword() {

            password_ = getDefaultInstance().getPassword();
            onChanged();
            return this;
        }

        /**
         * <code>string password = 3;</code>
         */
        public Builder setPasswordBytes(com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            password_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.newsroom.login.proto.rpc.LoginRequest)
    }

    // @@protoc_insertion_point(class_scope:com.newsroom.login.proto.rpc.LoginRequest)
    private static final com.newsroom.login.proto.rpc.LoginRequest DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.newsroom.login.proto.rpc.LoginRequest();
    }

    public static com.newsroom.login.proto.rpc.LoginRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginRequest> PARSER = new com.google.protobuf.AbstractParser<LoginRequest>() {
        public LoginRequest parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new LoginRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<LoginRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginRequest> getParserForType() {
        return PARSER;
    }

    public com.newsroom.login.proto.rpc.LoginRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
