// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.newsroom.login.proto.rpc;

public interface LoginResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.newsroom.login.proto.rpc.LoginResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool success = 1;</code>
     */
    boolean getSuccess();

    /**
     * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
     */
    boolean hasData();

    /**
     * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
     */
    com.newsroom.login.proto.rpc.Data getData();

    /**
     * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
     */
    com.newsroom.login.proto.rpc.DataOrBuilder getDataOrBuilder();
}
