// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.newsroom.login.proto.rpc;

/**
 * Protobuf type {@code com.newsroom.login.proto.rpc.LoginResponse}
 */
public final class LoginResponse extends com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.newsroom.login.proto.rpc.LoginResponse)
        LoginResponseOrBuilder {
    // Use LoginResponse.newBuilder() to construct.
    private LoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private LoginResponse() {
        success_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
        return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }

    private LoginResponse(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        int mutable_bitField0_ = 0;
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                case 0:
                    done = true;
                    break;
                default: {
                    if (!input.skipField(tag)) {
                        done = true;
                    }
                    break;
                }
                case 8: {

                    success_ = input.readBool();
                    break;
                }
                case 18: {
                    com.newsroom.login.proto.rpc.Data.Builder subBuilder = null;
                    if (data_ != null) {
                        subBuilder = data_.toBuilder();
                    }
                    data_ = input.readMessage(com.newsroom.login.proto.rpc.Data.parser(), extensionRegistry);
                    if (subBuilder != null) {
                        subBuilder.mergeFrom(data_);
                        data_ = subBuilder.buildPartial();
                    }

                    break;
                }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(e).setUnfinishedMessage(this);
        } finally {
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(com.newsroom.login.proto.rpc.LoginResponse.class,
                        com.newsroom.login.proto.rpc.LoginResponse.Builder.class);
    }

    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;

    /**
     * <code>bool success = 1;</code>
     */
    public boolean getSuccess() {
        return success_;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.newsroom.login.proto.rpc.Data data_;

    /**
     * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
     */
    public boolean hasData() {
        return data_ != null;
    }

    /**
     * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
     */
    public com.newsroom.login.proto.rpc.Data getData() {
        return data_ == null ? com.newsroom.login.proto.rpc.Data.getDefaultInstance() : data_;
    }

    /**
     * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
     */
    public com.newsroom.login.proto.rpc.DataOrBuilder getDataOrBuilder() {
        return getData();
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1)
            return true;
        if (isInitialized == 0)
            return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
        if (success_ != false) {
            output.writeBool(1, success_);
        }
        if (data_ != null) {
            output.writeMessage(2, getData());
        }
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1)
            return size;

        size = 0;
        if (success_ != false) {
            size += com.google.protobuf.CodedOutputStream.computeBoolSize(1, success_);
        }
        if (data_ != null) {
            size += com.google.protobuf.CodedOutputStream.computeMessageSize(2, getData());
        }
        memoizedSize = size;
        return size;
    }

    private static final long serialVersionUID = 0L;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof com.newsroom.login.proto.rpc.LoginResponse)) {
            return super.equals(obj);
        }
        com.newsroom.login.proto.rpc.LoginResponse other = (com.newsroom.login.proto.rpc.LoginResponse) obj;

        boolean result = true;
        result = result && (getSuccess() == other.getSuccess());
        result = result && (hasData() == other.hasData());
        if (hasData()) {
            result = result && getData().equals(other.getData());
        }
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(getSuccess());
        if (hasData()) {
            hash = (37 * hash) + DATA_FIELD_NUMBER;
            hash = (53 * hash) + getData().hashCode();
        }
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseDelimitedFrom(java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input);
    }

    public static com.newsroom.login.proto.rpc.LoginResponse parseFrom(com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3.parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(com.newsroom.login.proto.rpc.LoginResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code com.newsroom.login.proto.rpc.LoginResponse}
     */
    public static final class Builder extends com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:com.newsroom.login.proto.rpc.LoginResponse)
            com.newsroom.login.proto.rpc.LoginResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
            return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(com.newsroom.login.proto.rpc.LoginResponse.class,
                            com.newsroom.login.proto.rpc.LoginResponse.Builder.class);
        }

        // Construct using com.newsroom.login.proto.rpc.LoginResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            success_ = false;

            if (dataBuilder_ == null) {
                data_ = null;
            } else {
                data_ = null;
                dataBuilder_ = null;
            }
            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
            return com.newsroom.login.proto.rpc.Login.internal_static_com_newsroom_login_proto_rpc_LoginResponse_descriptor;
        }

        public com.newsroom.login.proto.rpc.LoginResponse getDefaultInstanceForType() {
            return com.newsroom.login.proto.rpc.LoginResponse.getDefaultInstance();
        }

        public com.newsroom.login.proto.rpc.LoginResponse build() {
            com.newsroom.login.proto.rpc.LoginResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public com.newsroom.login.proto.rpc.LoginResponse buildPartial() {
            com.newsroom.login.proto.rpc.LoginResponse result = new com.newsroom.login.proto.rpc.LoginResponse(this);
            result.success_ = success_;
            if (dataBuilder_ == null) {
                result.data_ = data_;
            } else {
                result.data_ = dataBuilder_.build();
            }
            onBuilt();
            return result;
        }

        public Builder clone() {
            return (Builder) super.clone();
        }

        public Builder setField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.setField(field, value);
        }

        public Builder clearField(com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }

        public Builder clearOneof(com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }

        public Builder setRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, int index,
                Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(com.google.protobuf.Descriptors.FieldDescriptor field, Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof com.newsroom.login.proto.rpc.LoginResponse) {
                return mergeFrom((com.newsroom.login.proto.rpc.LoginResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(com.newsroom.login.proto.rpc.LoginResponse other) {
            if (other == com.newsroom.login.proto.rpc.LoginResponse.getDefaultInstance())
                return this;
            if (other.getSuccess() != false) {
                setSuccess(other.getSuccess());
            }
            if (other.hasData()) {
                mergeData(other.getData());
            }
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            com.newsroom.login.proto.rpc.LoginResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (com.newsroom.login.proto.rpc.LoginResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private boolean success_;

        /**
         * <code>bool success = 1;</code>
         */
        public boolean getSuccess() {
            return success_;
        }

        /**
         * <code>bool success = 1;</code>
         */
        public Builder setSuccess(boolean value) {

            success_ = value;
            onChanged();
            return this;
        }

        /**
         * <code>bool success = 1;</code>
         */
        public Builder clearSuccess() {

            success_ = false;
            onChanged();
            return this;
        }

        private com.newsroom.login.proto.rpc.Data data_ = null;
        private com.google.protobuf.SingleFieldBuilderV3<com.newsroom.login.proto.rpc.Data, com.newsroom.login.proto.rpc.Data.Builder, com.newsroom.login.proto.rpc.DataOrBuilder> dataBuilder_;

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public boolean hasData() {
            return dataBuilder_ != null || data_ != null;
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public com.newsroom.login.proto.rpc.Data getData() {
            if (dataBuilder_ == null) {
                return data_ == null ? com.newsroom.login.proto.rpc.Data.getDefaultInstance() : data_;
            } else {
                return dataBuilder_.getMessage();
            }
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public Builder setData(com.newsroom.login.proto.rpc.Data value) {
            if (dataBuilder_ == null) {
                if (value == null) {
                    throw new NullPointerException();
                }
                data_ = value;
                onChanged();
            } else {
                dataBuilder_.setMessage(value);
            }

            return this;
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public Builder setData(com.newsroom.login.proto.rpc.Data.Builder builderForValue) {
            if (dataBuilder_ == null) {
                data_ = builderForValue.build();
                onChanged();
            } else {
                dataBuilder_.setMessage(builderForValue.build());
            }

            return this;
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public Builder mergeData(com.newsroom.login.proto.rpc.Data value) {
            if (dataBuilder_ == null) {
                if (data_ != null) {
                    data_ = com.newsroom.login.proto.rpc.Data.newBuilder(data_).mergeFrom(value).buildPartial();
                } else {
                    data_ = value;
                }
                onChanged();
            } else {
                dataBuilder_.mergeFrom(value);
            }

            return this;
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public Builder clearData() {
            if (dataBuilder_ == null) {
                data_ = null;
                onChanged();
            } else {
                data_ = null;
                dataBuilder_ = null;
            }

            return this;
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public com.newsroom.login.proto.rpc.Data.Builder getDataBuilder() {

            onChanged();
            return getDataFieldBuilder().getBuilder();
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        public com.newsroom.login.proto.rpc.DataOrBuilder getDataOrBuilder() {
            if (dataBuilder_ != null) {
                return dataBuilder_.getMessageOrBuilder();
            } else {
                return data_ == null ? com.newsroom.login.proto.rpc.Data.getDefaultInstance() : data_;
            }
        }

        /**
         * <code>.com.newsroom.login.proto.rpc.Data data = 2;</code>
         */
        private com.google.protobuf.SingleFieldBuilderV3<com.newsroom.login.proto.rpc.Data, com.newsroom.login.proto.rpc.Data.Builder, com.newsroom.login.proto.rpc.DataOrBuilder> getDataFieldBuilder() {
            if (dataBuilder_ == null) {
                dataBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<com.newsroom.login.proto.rpc.Data, com.newsroom.login.proto.rpc.Data.Builder, com.newsroom.login.proto.rpc.DataOrBuilder>(
                        getData(), getParentForChildren(), isClean());
                data_ = null;
            }
            return dataBuilder_;
        }

        public final Builder setUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        public final Builder mergeUnknownFields(final com.google.protobuf.UnknownFieldSet unknownFields) {
            return this;
        }

        // @@protoc_insertion_point(builder_scope:com.newsroom.login.proto.rpc.LoginResponse)
    }

    // @@protoc_insertion_point(class_scope:com.newsroom.login.proto.rpc.LoginResponse)
    private static final com.newsroom.login.proto.rpc.LoginResponse DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new com.newsroom.login.proto.rpc.LoginResponse();
    }

    public static com.newsroom.login.proto.rpc.LoginResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LoginResponse> PARSER = new com.google.protobuf.AbstractParser<LoginResponse>() {
        public LoginResponse parsePartialFrom(com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new LoginResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<LoginResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LoginResponse> getParserForType() {
        return PARSER;
    }

    public com.newsroom.login.proto.rpc.LoginResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
