// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: login.proto

package com.newsroom.login.proto.rpc;

public interface LoginRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.newsroom.login.proto.rpc.LoginRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string mailID = 1;</code>
     */
    java.lang.String getMailID();

    /**
     * <code>string mailID = 1;</code>
     */
    com.google.protobuf.ByteString getMailIDBytes();

    /**
     * <code>string mob = 2;</code>
     */
    java.lang.String getMob();

    /**
     * <code>string mob = 2;</code>
     */
    com.google.protobuf.ByteString getMobBytes();

    /**
     * <code>string password = 3;</code>
     */
    java.lang.String getPassword();

    /**
     * <code>string password = 3;</code>
     */
    com.google.protobuf.ByteString getPasswordBytes();
}
